/**
 * pre-deploy-cleanup.ts
 *
 * Cleans up the `out/` directory before deploying to Cloudflare Pages:
 *
 * 1. Removes Next.js RSC payload (.txt) files — generated by `output: "export"`,
 *    only needed for client-side SPA navigation, not for direct URL access.
 *
 * 2. Removes `out/images/` entirely — local WebP sprites that are only present
 *    when `R2_PUBLIC_URL` was empty during sync. When sync runs with a valid
 *    R2_PUBLIC_URL, all thumbWebp fields are absolute R2 CDN URLs
 *    (https://workwear-images.databiz.app/...) and no local copies are needed.
 *    Images are served from R2 CDN (same Cloudflare edge network — no latency
 *    difference vs. Pages-served assets).
 *
 * Guard: exits with code 1 if model-summary-core.json still contains relative
 * image paths, meaning sync was run without R2_PUBLIC_URL set.
 *
 * Without cleanup: ~23k files (over Cloudflare Pages 20k limit)
 * After cleanup:   ~9.5k files (comfortably under the limit)
 *
 * Idempotent: safe to run multiple times.
 */

import { readdirSync, statSync, unlinkSync, rmSync, existsSync, readFileSync } from "fs";
import path from "path";

const OUT_DIR = path.join(process.cwd(), "out");

// ---------------------------------------------------------------------------
// Guard: verify thumbWebp URLs are absolute (R2 CDN), not relative paths
// ---------------------------------------------------------------------------

const coreSummaryPath = path.join(OUT_DIR, "data", "model-summary-core.json");
if (existsSync(coreSummaryPath)) {
  const models: Array<{ slug: string; thumbWebp?: string }> = JSON.parse(
    readFileSync(coreSummaryPath, "utf8")
  );
  const relativeSample = models.filter(
    (m) => m.thumbWebp && m.thumbWebp.startsWith("/")
  ).slice(0, 3);

  if (relativeSample.length > 0) {
    console.error(
      "ERROR: model-summary-core.json contains relative image paths (R2_PUBLIC_URL was empty during sync)."
    );
    console.error("Fix: run sync with R2_PUBLIC_URL set:");
    console.error(
      "  R2_PUBLIC_URL=https://workwear-images.databiz.app npm run sync:force"
    );
    console.error("Relative paths found:", relativeSample.map((m) => m.thumbWebp));
    process.exit(1);
  }
  console.log(
    `Image URL check: OK — thumbWebp fields are absolute R2 URLs.`
  );
} else {
  console.warn(
    "Warning: out/data/model-summary-core.json not found — skipping image URL guard."
  );
}

// ---------------------------------------------------------------------------
// Step 1: Remove RSC payload (.txt) files
// ---------------------------------------------------------------------------

function findTxtFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = path.join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      results.push(...findTxtFiles(fullPath));
    } else if (entry.endsWith(".txt")) {
      results.push(fullPath);
    }
  }
  return results;
}

const txtFiles = findTxtFiles(OUT_DIR);
if (txtFiles.length === 0) {
  console.log("RSC payload (.txt) files: none found — already clean.");
} else {
  console.log(`Removing ${txtFiles.length} RSC payload (.txt) files...`);
  for (const file of txtFiles) {
    unlinkSync(file);
  }
}

// ---------------------------------------------------------------------------
// Step 2: Remove out/images/ (local WebP sprites — served from R2 CDN instead)
// ---------------------------------------------------------------------------

const IMAGES_DIR = path.join(OUT_DIR, "images");
if (existsSync(IMAGES_DIR)) {
  // Count files before removal for reporting
  function countFilesInDir(dir: string): number {
    let count = 0;
    for (const entry of readdirSync(dir)) {
      const fullPath = path.join(dir, entry);
      if (statSync(fullPath).isDirectory()) {
        count += countFilesInDir(fullPath);
      } else {
        count++;
      }
    }
    return count;
  }
  const imageCount = countFilesInDir(IMAGES_DIR);
  rmSync(IMAGES_DIR, { recursive: true, force: true });
  console.log(
    `Removed out/images/ (${imageCount} local WebP sprites — images served from R2 CDN).`
  );
} else {
  console.log("out/images/: not present — nothing to remove.");
}

// ---------------------------------------------------------------------------
// Final file count + limit check
// ---------------------------------------------------------------------------

function countFiles(dir: string): number {
  let count = 0;
  for (const entry of readdirSync(dir)) {
    const fullPath = path.join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      count += countFiles(fullPath);
    } else {
      count++;
    }
  }
  return count;
}

const remaining = countFiles(OUT_DIR);
console.log(`Done. Remaining files in out/: ${remaining}`);

if (remaining >= 20000) {
  console.error(
    `ERROR: ${remaining} files still exceeds the Cloudflare Pages 20k limit!`
  );
  process.exit(1);
}
